/**
 * WAVE 173 — R137.1 RENDERED-DOM PROOF THAT THE CHECKLIST STOPS LYING.
 *
 * ══════════════════════════════════════════════════════════════════════════════
 * WHY THIS FILE HAS TO EXIST
 * ══════════════════════════════════════════════════════════════════════════════
 * The server suite proves the PATCH now answers 409 with a sentence. It cannot
 * prove the partner ever reads that sentence — and the defect being fixed is
 * precisely a defect of what the partner is TOLD. Before wave 173 the screen
 * showed a fresh "Saved" timestamp and a ticked box for a write that stored
 * nothing. If the refusal were to arrive and the page swallowed it, the partner
 * would be no better off than before: a tick that does not persist, with no
 * explanation. R137.1 is the reason this is asserted on the mounted component.
 *
 * NOTHING IN THE DATA PATH IS MOCKED. The page calls global `fetch` directly
 * (`OnboardingChecklistPage.tsx:145` `fetchJson`), so the bridge here replaces
 * `global.fetch` with one that drives the REAL express app over supertest,
 * against the REAL SQLite schema and the REAL registered onboarding routes. The
 * 409 the DOM renders is generated by the production handler, not by a stub.
 *
 * WHAT IT PROVES, AS SENTENCES:
 *   1. the refusal reaches the SCREEN — the server's own sentence is rendered in
 *      the error banner, not swallowed and not replaced by an HTTP number;
 *   2. no SCREAMING_SNAKE enum code is shown to the partner anywhere on the page;
 *   3. the page does NOT claim it saved — no fresh "Saved" timestamp appears
 *      after a refused write, which is the false success the wave removes;
 *   4. the tick does not stay on screen as if it were durable;
 *   5. the checklist still renders its items, so the refusal breaks no read path.
 *
 * FAIL-BEFORE: with the wave-173 refusal reverted the PATCH answers 200 ok, so
 * no banner renders, `error-banner` is absent, and tests 1-4 fail on
 * `getByTestId` / on finding the sentence. Recorded in
 * `build_log/wave173/W173_DOM_FAIL_BEFORE.txt`.
 *
 * NEVER MUTATES data.db / test.db — ordinary in-memory test handle.
 */
import type { ReactNode } from "react";
import { describe, it, expect, vi, beforeAll, afterEach } from "vitest";
import { render, screen, fireEvent, waitFor, cleanup } from "@testing-library/react";
import express, { type Express } from "express";
import request from "supertest";
import { RoleProvider } from "@/lib/role";
import { getDb, rawDb } from "../../../../../server/db/connection";
import { seedDemoData } from "../../../../../server/lib/seedDemoData";
import {
  seedTestPartnerSandbox,
  TEST_PARTNER_ID,
  TEST_PARTNER_USERS,
} from "../../../../../server/partnerWorkspaceStore";
import { PARTNER_ONBOARDING_STATE_NOT_STORABLE_COPY } from "../../../../../server/consortiumApplyStore";
import PartnerOnboardingChecklistPage from "../OnboardingChecklistPage";

const PARTNER_A = TEST_PARTNER_ID;
const MANAGING_A = TEST_PARTNER_USERS.managing.userId;

let app: Express;

/* ── the mocks, and none of them touch the data path ───────────────────────── */
vi.mock("@/components/partner/PartnerShell", () => ({
  PartnerShell: ({ children }: { children?: ReactNode }) => <div>{children}</div>,
  PartnerEmptyState: ({ title }: { title?: string }) => <div>{title ?? ""}</div>,
}));

const toastMock = vi.fn();
vi.mock("@/hooks/use-toast", () => ({ useToast: () => ({ toast: toastMock }) }));

/* THE IDENTITY OBJECT IS HOISTED AND FROZEN ON PURPOSE. An earlier draft of this
   mock returned a fresh object literal on every call, and the page's
   `useEffect(..., [load, role.ready, role.identity])`
   (`OnboardingChecklistPage.tsx:207-209`) therefore re-ran `load()` on every
   render — an unbounded GET loop that held `loading` true, which in turn kept
   `disabled={loading || saving}` set on every toggle, so the clicks under test
   were silent no-ops. Referential stability is a REQUIREMENT of this harness,
   not a tidiness preference. */
const ROLE_IDENTITY = Object.freeze({
  partnerId: "ac_consortium_partner_test",
  tier: "builder",
  subRole: "managing_partner",
  identity: Object.freeze({
    userId: "u_partner_managing_test",
    email: "p@w173dom.test",
    name: "W173 DOM Managing",
  }),
});
const ROLE_RESULT = Object.freeze({ ready: true, error: null, identity: ROLE_IDENTITY });
vi.mock("@/lib/partner/useRequirePartnerRole", () => ({
  useRequirePartnerRole: () => ROLE_RESULT,
}));

vi.mock("@/lib/sseClient", () => ({ useCollectiveStream: () => undefined }));

/* THE BRIDGE — real HTTP, in process, over the real handler.
   `fetchJson` reads `r.ok`, `r.status` and `r.json()`, and `serverRefusalText`
   reads the parsed body, so those are the surfaces this must present faithfully.
   Nothing is short-circuited: a 409 arrives here because the production handler
   produced one. */
const httpCalls: Array<{ method: string; url: string; status: number }> = [];

beforeAll(async () => {
  process.env.COLLECTIVE_ENABLED = "1";
  await seedDemoData(getDb());
  seedTestPartnerSandbox({ force: true });

  const { registerPartnerOnboardingRoutes } = await import(
    "../../../../../server/consortiumApplyStore"
  );
  const { installV14TestIdentity } = await import("../../../../../server/__tests__/_v14TestIdentity");
  app = express();
  app.use(express.json());
  installV14TestIdentity(app, { defaultIdentity: false });
  registerPartnerOnboardingRoutes(app);

  (global as any).fetch = async (url: string, init?: RequestInit) => {
    const method = String(init?.method ?? "GET").toLowerCase();
    let r = (request(app) as any)[method](String(url))
      .set("x-user-id", MANAGING_A)
      .set("x-actor-user-id", MANAGING_A);
    if (init?.body !== undefined && init?.body !== null) {
      r = r.set("content-type", "application/json").send(String(init.body));
    }
    const res = await r;
    httpCalls.push({ method: method.toUpperCase(), url: String(url), status: res.status });
    const bodyText = JSON.stringify(res.body ?? {});
    return {
      ok: res.status >= 200 && res.status < 300,
      status: res.status,
      statusText: String(res.status),
      headers: { get: (k: string) => (k.toLowerCase() === "content-type" ? "application/json" : null) },
      json: async () => res.body,
      text: async () => bodyText,
      clone() {
        return this;
      },
    } as unknown as Response;
  };
}, 60_000);

afterEach(() => cleanup());

/** Mount the page and wait for its initial load to settle. */
async function mountChecklist(): Promise<void> {
  /* The page's shell reads the role context (`client/src/lib/role.tsx:13` throws
     "RoleProvider missing" without it). The REAL provider is used, not a stub —
     it holds no data this test depends on. */
  render(
    <RoleProvider>
      <PartnerOnboardingChecklistPage />
    </RoleProvider>,
  );
  await waitFor(
    () =>
      expect(
        httpCalls.some((c) => c.url.includes("/api/partner/onboarding/state") && c.method === "GET"),
      ).toBe(true),
    { timeout: 5000 },
  );
  /* The progress badge only renders once loading has finished. */
  await waitFor(() => expect(screen.getByTestId("badge-progress")).toBeTruthy(), { timeout: 5000 });
}

/** Tick a self-declared item, which triggers the PATCH under test. */
async function tick(key: string): Promise<void> {
  const toggle = await screen.findByTestId(`toggle-${key}`, {}, { timeout: 5000 });
  /* The button carries `disabled={loading || saving}`
     (`OnboardingChecklistPage.tsx:359`), and a click on a disabled button is a
     silent no-op — an earlier draft of this file waited five seconds for a PATCH
     that had never been dispatched. Wait for it to be live before clicking. */
  await waitFor(() => expect((toggle as HTMLButtonElement).disabled).toBe(false), {
    timeout: 5000,
  });
  fireEvent.click(toggle);
  await waitFor(
    () =>
      expect(
        httpCalls.some((c) => c.url.includes("/api/partner/onboarding/state") && c.method === "PATCH"),
      ).toBe(true),
    { timeout: 5000 },
  );
}

describe("wave173 · rendered DOM — a refused tick says so on the screen", () => {
  it("DOM0 (precondition) the table really is empty, so the PATCH really cannot store", () => {
    const row = rawDb()
      .prepare(`SELECT COUNT(*) AS n FROM partner_organizations WHERE id = ?`)
      .get(PARTNER_A) as { n: number };
    /* Without this, DOM1 could pass because of some unrelated error. */
    expect(row.n).toBe(0);
  }, 20_000);

  it("DOM1: the server's own sentence is rendered in the error banner", async () => {
    await mountChecklist();
    await tick("billing_contact");

    const banner = await screen.findByTestId("error-banner", {}, { timeout: 5000 });
    const shown = String(banner.textContent ?? "");

    /* THE CLAIM OF THE WAVE, checked where a person would read it. The page
       renders the server's message through `serverRefusalText`, which appends
       "(refusal code: …)", so this is a containment assertion on the sentence
       itself rather than an equality assertion on the whole banner. */
    expect(shown).toContain("could not be saved");
    expect(shown).toContain("has not been kept");
    /* A long stretch of the server's literal copy, so a paraphrase on the client
       — a second, drifting source of truth — would fail this. */
    expect(PARTNER_ONBOARDING_STATE_NOT_STORABLE_COPY).toContain("could not be saved");
    expect(shown.length).toBeGreaterThan(60);
  }, 20_000);

  it("DOM2: the partner is never shown a raw enum code as their explanation", async () => {
    await mountChecklist();
    await tick("team_invites");
    const banner = await screen.findByTestId("error-banner", {}, { timeout: 5000 });
    const shown = String(banner.textContent ?? "");

    /* `serverRefusalText` deliberately appends a parenthesised code for support,
       so the code may appear ONCE in that trailing form. What must not happen is
       the code standing in PLACE of the sentence, which is the pre-wave-73
       failure mode this wave must not reintroduce. The sentence must come first. */
    const codeAt = shown.indexOf("ONBOARDING_STATE_NOT_STORABLE");
    const sentenceAt = shown.indexOf("could not be saved");
    expect(sentenceAt).toBeGreaterThanOrEqual(0);
    if (codeAt >= 0) expect(sentenceAt).toBeLessThan(codeAt);
    /* No internal table or column name is put in front of a partner IN THE PROSE.
       Scoped to the prose deliberately: `serverRefusalText` appends
       "(refusal code: ONBOARDING_STATE_NOT_STORABLE)" for support, and that code
       lowercased of course contains "onboarding_state". Asserting over the whole
       banner would therefore fail on the sanctioned support suffix rather than on
       a real leak, so the sentence is separated from the suffix first. */
    const prose = shown.split("(refusal code:")[0];
    expect(prose.length).toBeGreaterThan(60); // anti-vacuity: the split kept the sentence
    expect(prose.toLowerCase()).not.toContain("partner_organizations");
    expect(prose.toLowerCase()).not.toContain("onboarding_state");
    expect(prose).not.toMatch(/[A-Z]{3,}_[A-Z]{3,}/);
    expect(shown).not.toContain("HTTP 409");
  }, 20_000);

  it("DOM3: the page does NOT claim it saved — no fresh saved-at timestamp appears", async () => {
    await mountChecklist();
    /* The false success being removed was a rendered "Saved …" line after a write
       that stored nothing. Assert on the presence of the node, not on its text,
       so a change of date format cannot make this pass hollowly. */
    expect(screen.queryByTestId("text-saved-at")).toBeNull();
    await tick("data_retention_acked");
    await screen.findByTestId("error-banner", {}, { timeout: 5000 });
    expect(screen.queryByTestId("text-saved-at")).toBeNull();
  }, 20_000);

  it("DOM4: the refused tick does not remain on screen as if it were durable", async () => {
    await mountChecklist();
    await tick("sso_configured");
    await screen.findByTestId("error-banner", {}, { timeout: 5000 });
    /* The page applies ticks optimistically and rolls back on failure (its own
       copy says so). After a refusal the item must not read as done, or the
       partner is misled exactly as before — just with a banner beside it. */
    /* The item's done-ness is exposed on the toggle button as `aria-pressed`
       (`OnboardingChecklistPage.tsx:360`). `status-*` exists only for the
       read-only agreement row, so this reads the attribute the page really sets. */
    const toggle = await screen.findByTestId("toggle-sso_configured", {}, { timeout: 5000 });
    await waitFor(() => expect(toggle.getAttribute("aria-pressed")).toBe("false"));
  }, 20_000);

  it("DOM5: the checklist itself still renders, so the refusal breaks no read path", async () => {
    await mountChecklist();
    /* Anti-vacuity for the whole file: if the page rendered nothing, every
       queryByTestId-is-null assertion above would pass for the wrong reason. */
    expect(screen.getByTestId("badge-progress")).toBeTruthy();
    expect(screen.getByTestId("item-billing_contact")).toBeTruthy();
    expect(screen.getByTestId("item-signed_partner_agreement")).toBeTruthy();
  }, 20_000);
});
