/* ════════════════════════════════════════════════════════════════════════════
   WAVE 123 · FINDING 1 — THE SECOND TERM-SHEET GENERATOR NAMED A SECURITY THE
                          ROUND DOES NOT USE.
   ════════════════════════════════════════════════════════════════════════════
   WHAT WAS BROKEN, IN THE SHIPPED SOURCE. `buildTermSheetMarkdown` in
   `server/track1Routes.ts` — reachable through
   `POST /api/founder/term-sheets/generate`, whose output is PERSISTED into the
   `term_sheets` table and served back by
   `GET /api/founder/term-sheets/:id/download` — printed, verbatim:

       `**Company ID:** ${round.companyId}`
       `**Pre-Money Valuation:** ${round.preMoney?.toLocaleString() ?? "N/A"}`
       `**Price Per Share:** ${round.pricePerShare ?? "N/A"}`
       `**Instrument:** ${round.instrument ?? "SAFE"}`
       ...Object.entries(terms).map(([k, v]) => `  - **${k}:** ${v}`)
       `*Generated by Capavate v25.0 at ${nowIso()}*`

   Five defects, of which the first is not cosmetic: a round with no instrument
   on record was published to counsel AS A SAFE. Wave 117 hardened the OTHER
   generator (`server/lib/pdfGenerators.ts`) and never touched this one.

   HOW THIS SUITE PROVES THE FIX. Group (A) is the refusal: the generator must
   answer "no document" rather than invent the security. (B) prints the
   instrument through the SHARED label table, never a raw token and never a
   guess. (C) names the company and leaks no internal id. (D) is the money rule —
   every figure carries its currency, no currency is invented where the column is
   null (which is the ordinary state of `rounds.currency` on this tree), and an
   unstored figure reads "Not recorded on this round". (E) forbids a raw DB key
   as a term label and pins the liquidation preference to Wave 111's ONE reader.
   (F) forbids a hardcoded version. (G) source-locks the order of the route: the
   refusal returns BEFORE the INSERT, so a refused document is never stored.

   FAIL-BEFORE PROOF. Every assertion here was run against the pre-wave tree,
   restored byte-for-byte afterwards and verified by sha256; the verbatim output
   is in `build_log/wave123/W123_TESTS.md`.
   ════════════════════════════════════════════════════════════════════════════ */
import { describe, it, expect, vi } from "vitest";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";

/* The company name comes from the platform's company store. It is doubled so the
   suite states a name and an id it fully controls, and so the "the document must
   not contain the id" assertion cannot pass by accident. */
vi.mock("../multiCompanyStore", async (importOriginal) => {
  const actual = await importOriginal<typeof import("../multiCompanyStore")>();
  return {
    ...actual,
    getCompanyNameById: (id: string) =>
      id === "co_w123_named" ? "NovaPay Labs Inc." :
      id === "co_w123_name_is_id" ? "co_w123_name_is_id" :
      null,
  };
});

import { buildTermSheetDocument } from "../track1Routes";

const TRACK1_SRC = readFileSync(resolve(__dirname, "../track1Routes.ts"), "utf8");
const PKG_VERSION = (
  JSON.parse(readFileSync(resolve(__dirname, "../../package.json"), "utf8")) as { version: string }
).version;

/** The shape `getRoundById` returns, as far as this generator reads it. Cast at
 *  the call site because the suite deliberately builds rounds the type forbids
 *  (a missing instrument is exactly the case under test). */
type RoundLike = Record<string, unknown>;

function round(over: RoundLike = {}): RoundLike {
  return {
    id: "rnd_w123",
    companyId: "co_w123_named",
    name: "Series A",
    type: "seed",
    state: "active",
    instrument: "safe_post",
    currency: "USD",
    targetAmount: 5_000_000,
    preMoney: 20_000_000,
    pricePerShare: 2,
    closeDate: "2026-11-30",
    termsSummary: "Standard Series A terms.",
    liquidationPreference: "1x non-participating",
    ...over,
  };
}

/* eslint-disable @typescript-eslint/no-explicit-any */
const build = (r: RoundLike | null) => buildTermSheetDocument(r as any);

function markdownOf(r: RoundLike): string {
  const doc = build(r);
  if (!doc.ok) throw new Error(`expected a document, got refusal ${doc.refusal}`);
  return doc.markdown;
}

/* ── (A) THE REFUSAL — THE DEFECT THAT MATTERS ─────────────────────────────── */
describe("(A) a round with no instrument on record produces NO document", () => {
  for (const missing of [null, undefined, "", "   "]) {
    it(`refuses when instrument is ${JSON.stringify(missing)}`, () => {
      const doc = build(round({ instrument: missing }));
      expect(doc.ok).toBe(false);
      if (doc.ok) return;
      expect(doc.refusal).toBe("INSTRUMENT_NOT_ON_RECORD");
      /* THE POINT OF THE WHOLE WAVE: the word SAFE must not appear as this
         round's instrument, in the document or in the refusal. */
      expect(doc.message).not.toMatch(/\bSAFE\b/);
      expect(doc.message.toLowerCase()).toContain("instrument");
    });
  }

  it("does not fall back to the ROUND type as if it were an instrument", () => {
    const doc = build(round({ instrument: null, type: "safe" }));
    expect(doc.ok).toBe(false);
  });

  it("refuses for a round that does not exist, instead of emitting a document", () => {
    const doc = build(null);
    expect(doc.ok).toBe(false);
    if (doc.ok) return;
    expect(doc.refusal).toBe("ROUND_NOT_FOUND");
  });

  it("the shipped source contains no fabricated instrument default", () => {
    /* Read only the generator, and only its executable half: the explanatory
       comment above it QUOTES the defective expression on purpose, and the file's
       other `instrument ?? ""` sites coalesce to the EMPTY string, which is a
       refusal input and not a fabricated instrument. */
    const gen = TRACK1_SRC.slice(
      TRACK1_SRC.indexOf("export function buildTermSheetDocument"),
      TRACK1_SRC.indexOf("function handleTermSheetGenerate"),
    );
    expect(gen).not.toMatch(/instrument\s*\?\?\s*"[^"]/);
    expect(gen).not.toMatch(/\?\?\s*"SAFE"/);
  });
});

/* ── (B) A REAL INSTRUMENT, THROUGH THE SHARED LABEL TABLE ─────────────────── */
describe("(B) the instrument printed is the one on record, in counsel's words", () => {
  it("prints a human label for a post-money SAFE and not the raw token", () => {
    const md = markdownOf(round({ instrument: "safe_post" }));
    const line = md.split("\n").find((l) => l.startsWith("**Instrument:**"))!;
    expect(line).toBeDefined();
    expect(line).not.toContain("safe_post");
    expect(line.toLowerCase()).toContain("safe");
  });

  it("a priced preferred round is never described as a SAFE", () => {
    const md = markdownOf(round({ instrument: "preferred" }));
    const line = md.split("\n").find((l) => l.startsWith("**Instrument:**"))!;
    expect(line).not.toMatch(/\bSAFE\b/);
  });

  it("an unrecognised stored instrument is humanised, not dropped and not replaced", () => {
    const md = markdownOf(round({ instrument: "convertible_note_2026" }));
    const line = md.split("\n").find((l) => l.startsWith("**Instrument:**"))!;
    expect(line).not.toMatch(/\bSAFE\b/);
    expect(line).not.toContain("convertible_note_2026");
    expect(line.toLowerCase()).toContain("convertible");
  });
});

/* ── (C) THE PARTY IS A COMPANY, NOT A PRIMARY KEY ─────────────────────────── */
describe("(C) the document names the company and leaks no internal identifier", () => {
  it("prints the company NAME", () => {
    const md = markdownOf(round());
    expect(md).toContain("**Company:** NovaPay Labs Inc.");
  });

  it("prints the company id NOWHERE, and no `Company ID` row survives", () => {
    const md = markdownOf(round());
    expect(md).not.toContain("co_w123_named");
    expect(md).not.toContain("Company ID");
    expect(md).not.toMatch(/\bco_[a-z0-9_]+/i);
    expect(md).not.toMatch(/\brnd_[a-z0-9_]+/i);
  });

  it("states the party is not on record rather than printing the id, when the name is unknown", () => {
    const md = markdownOf(round({ companyId: "co_w123_unknown" }));
    expect(md).toContain("**Company:** Not recorded on this round");
    expect(md).not.toContain("co_w123_unknown");
  });

  it("a stored name that is merely the id repeated is treated as no name at all", () => {
    const md = markdownOf(round({ companyId: "co_w123_name_is_id" }));
    expect(md).toContain("**Company:** Not recorded on this round");
    expect(md).not.toContain("co_w123_name_is_id");
  });
});

/* ── (D) MONEY ─────────────────────────────────────────────────────────────── */
describe("(D) every money figure carries its currency, and none is invented", () => {
  const MONEY_ROWS = ["**Target Amount:**", "**Pre-Money Valuation:**", "**Price Per Share:**"];

  it("a recorded currency appears on EVERY money row", () => {
    const md = markdownOf(round({ currency: "CAD" }));
    for (const row of MONEY_ROWS) {
      const line = md.split("\n").find((l) => l.startsWith(row))!;
      expect(line, row).toBeDefined();
      expect(line, row).toContain("CAD");
    }
    expect(md).toContain("**Currency:** CAD");
    /* The old document printed a bare `2` for price per share. */
    expect(md).not.toMatch(/\*\*Price Per Share:\*\*\s*[\d,.]+\s*$/m);
  });

  it("a CAD round is never printed as US dollars", () => {
    const md = markdownOf(round({ currency: "CAD" }));
    expect(md).not.toContain("USD");
    expect(md).not.toContain("$");
  });

  it("where the round records NO currency, no currency is invented and the gap is stated", () => {
    const md = markdownOf(round({ currency: null }));
    expect(md).toContain("**Currency:** Not recorded on this round");
    expect(md).not.toContain("USD");
    for (const row of MONEY_ROWS) {
      const line = md.split("\n").find((l) => l.startsWith(row))!;
      expect(line, row).toContain("currency not recorded on this round");
    }
  });

  it("no money row is ever a bare number", () => {
    for (const r of [round({ currency: "USD" }), round({ currency: null })]) {
      const md = markdownOf(r);
      for (const row of MONEY_ROWS) {
        const line = md.split("\n").find((l) => l.startsWith(row))!;
        const value = line.slice(row.length).trim();
        expect(/^[\d,.]+$/.test(value), `${row} printed bare: ${value}`).toBe(false);
      }
    }
  });

  it("an unstored figure reads 'Not recorded on this round', never N/A and never 0", () => {
    const md = markdownOf(round({ preMoney: null, pricePerShare: null, targetAmount: null }));
    for (const row of MONEY_ROWS) {
      const line = md.split("\n").find((l) => l.startsWith(row))!;
      expect(line, row).toBe(`${row} Not recorded on this round`);
    }
    expect(md).not.toContain("N/A");
    expect(md).not.toContain("$0");
  });

  it("an unstored close date reads the same sentence, not 'TBD'", () => {
    const md = markdownOf(round({ closeDate: null }));
    expect(md).toContain("**Close Date:** Not recorded on this round");
    expect(md).not.toContain("TBD");
  });

  it("the generator applies no Number()/parseInt/parseFloat to an amount", () => {
    const gen = TRACK1_SRC.slice(
      TRACK1_SRC.indexOf("export function buildTermSheetDocument"),
      TRACK1_SRC.indexOf("function handleTermSheetGenerate"),
    );
    expect(gen).not.toMatch(/\bparseFloat\s*\(/);
    expect(gen).not.toMatch(/\bparseInt\s*\(/);
    expect(gen).not.toMatch(/\bNumber\s*\(/);
  });
});

/* ── (E) TERMS ARE READ, NOT DUMPED ───────────────────────────────────────── */
describe("(E) no raw database key is ever a term label", () => {
  const RAW_KEYS = [
    "liqPrefMultiple",
    "capParticipation",
    "liquidationPreference",
    "proRataRights",
    "boardSeats",
    "termsSummary",
    "preMoney",
    "pricePerShare",
    "targetAmount",
    "closeDate",
    "companyId",
  ];

  it("a round carrying a full `terms` object prints none of its keys", () => {
    const md = markdownOf(
      round({
        terms: {
          liqPrefMultiple: 1,
          capParticipation: true,
          proRataRights: "yes",
          somethingUnlabelled: "42",
        },
      }),
    );
    for (const key of RAW_KEYS) {
      expect(md, key).not.toContain(key);
    }
  });

  it("the stored values are not silently dropped either — the document says they exist", () => {
    const md = markdownOf(round({ terms: { liqPrefMultiple: 1, capParticipation: true } }));
    expect(md).toMatch(/2 further values/);
    expect(md.toLowerCase()).toContain("terms tab");
  });

  it("the liquidation preference is stated through the ONE reader's sentence", () => {
    const md = markdownOf(round({ liquidationPreference: "1x non-participating" }));
    expect(md).toContain("**Liquidation preference:** 1x non-participating");
  });

  it("an unreadable liquidation preference is refused in words, not printed as a term", () => {
    const md = markdownOf(round({ liquidationPreference: "to be negotiated" }));
    const line = md.split("\n").find((l) => l.includes("Liquidation preference"))!;
    expect(line.toLowerCase()).toContain("cannot be read");
    expect(line).not.toMatch(/\d+x participating/);
  });

  it("a round with nothing recorded says so, for the preference and for governance", () => {
    const md = markdownOf(round({ liquidationPreference: null }));
    expect(md).toContain("Not recorded on this round");
  });

  it("the generator no longer dumps Object.entries of the terms bag", () => {
    const gen = TRACK1_SRC.slice(
      TRACK1_SRC.indexOf("export function buildTermSheetDocument"),
      TRACK1_SRC.indexOf("function handleTermSheetGenerate"),
    );
    expect(gen).not.toMatch(/Object\.entries\(\s*terms\s*\)/);
  });
});

/* ── (F) THE VERSION IS NOT TYPED INTO THIS FILE ───────────────────────────── */
describe("(F) the footer states the version the tree actually is", () => {
  it("prints package.json's version", () => {
    const md = markdownOf(round());
    expect(md).toContain(`Capavate v${PKG_VERSION}`);
  });

  it("does not print v25.0 on a v26 tree", () => {
    const md = markdownOf(round());
    expect(md).not.toContain("v25.0");
  });

  it("no version literal is hardcoded anywhere in the generator", () => {
    const gen = TRACK1_SRC.slice(
      TRACK1_SRC.indexOf("const TERM_SHEET_NOT_RECORDED"),
      TRACK1_SRC.indexOf("function handleTermSheetGenerate"),
    );
    const literals = gen.match(/"v?\d+\.\d+(\.\d+)?"/g) ?? [];
    expect(literals).toEqual([]);
  });

  it("APP_VERSION is honoured, so a deploy can pin what the document claims", () => {
    const prev = process.env.APP_VERSION;
    process.env.APP_VERSION = "99.99.99-w123";
    try {
      expect(markdownOf(round())).toContain("Capavate v99.99.99-w123");
    } finally {
      if (prev === undefined) delete process.env.APP_VERSION;
      else process.env.APP_VERSION = prev;
    }
  });
});

/* ── (G) A REFUSED DOCUMENT IS NEVER STORED ────────────────────────────────── */
describe("(G) the route refuses before it writes", () => {
  const handler = TRACK1_SRC.slice(
    TRACK1_SRC.indexOf("function handleTermSheetGenerate"),
    TRACK1_SRC.indexOf("function handleTermSheetGenerate") + 3000,
  );

  it("returns TERM_SHEET_REFUSED with the refusal name and the reason", () => {
    expect(handler).toContain("TERM_SHEET_REFUSED");
    expect(handler).toContain("refusal: built.refusal");
    expect(handler).toContain("message: built.message");
  });

  it("the refusal return happens BEFORE the INSERT into term_sheets", () => {
    const refuseAt = handler.indexOf("TERM_SHEET_REFUSED");
    const insertAt = handler.indexOf("INSERT INTO term_sheets");
    expect(refuseAt).toBeGreaterThan(-1);
    expect(insertAt).toBeGreaterThan(refuseAt);
  });

  it("the old generator name is gone, so no caller can reach the fabricating path", () => {
    expect(TRACK1_SRC).not.toContain("buildTermSheetMarkdown");
  });
});
