#!/usr/bin/env node
/**
 * scripts/generate_schema_reference.ts — v23.4.1 hotfix Task K
 *
 * Generates docs/SCHEMA_REFERENCE.md by introspecting the actual SQLite DB
 * using PRAGMA table_info() for each table. This is more accurate than
 * parsing shared/schema.ts with a regex, because it reflects the actual
 * deployed state (after migrations).
 *
 * Usage:
 *   npm run docs:schema
 *   npx tsx scripts/generate_schema_reference.ts
 *   npx tsx scripts/generate_schema_reference.ts --output docs/SCHEMA_REFERENCE.md
 *
 * Output file: docs/SCHEMA_REFERENCE.md (configurable via --output)
 */

import * as fs from "node:fs";
import * as path from "node:path";
import { rawDb } from "../server/db/connection";

/* ------------------------------------------------------------------ */
/* CLI                                                                  */
/* ------------------------------------------------------------------ */
const argv = process.argv.slice(2);
let outputPath = path.join(process.cwd(), "docs", "SCHEMA_REFERENCE.md");
for (let i = 0; i < argv.length; i++) {
  if (argv[i] === "--output" && argv[i + 1]) outputPath = argv[++i]!;
  else if (argv[i]?.startsWith("--output=")) outputPath = argv[i]!.slice("--output=".length);
}

/* ------------------------------------------------------------------ */
/* Introspect DB                                                        */
/* ------------------------------------------------------------------ */
interface ColInfo {
  cid: number;
  name: string;
  type: string;
  notnull: number;
  dflt_value: string | null;
  pk: number;
}

interface IndexInfo {
  name: string;
  unique: number;
  origin: string;
  columns: string[];
}

function introspectDb() {
  const db = rawDb();

  const tables = (
    db
      .prepare(`SELECT name FROM sqlite_master WHERE type='table' ORDER BY name`)
      .all() as { name: string }[]
  ).map((r) => r.name).filter((n) => !n.startsWith("sqlite_"));

  const result: {
    tableName: string;
    columns: ColInfo[];
    indexes: IndexInfo[];
  }[] = [];

  for (const tableName of tables) {
    const columns = db.prepare(`PRAGMA table_info(${tableName})`).all() as ColInfo[];
    const rawIndexes = db.prepare(`PRAGMA index_list(${tableName})`).all() as {
      seq: number;
      name: string;
      unique: number;
      origin: string;
      partial: number;
    }[];

    const indexes: IndexInfo[] = [];
    for (const idx of rawIndexes) {
      const idxCols = db
        .prepare(`PRAGMA index_info(${idx.name})`)
        .all() as { seqno: number; cid: number; name: string }[];
      indexes.push({
        name: idx.name,
        unique: idx.unique,
        origin: idx.origin,
        columns: idxCols.map((c) => c.name),
      });
    }

    result.push({ tableName, columns, indexes });
  }

  return result;
}

/* ------------------------------------------------------------------ */
/* Markdown generation                                                  */
/* ------------------------------------------------------------------ */
function generateMarkdown(
  tables: ReturnType<typeof introspectDb>,
): string {
  const lines: string[] = [];
  const now = new Date().toISOString();

  lines.push("# Capavate Schema Reference");
  lines.push("");
  lines.push(`> Auto-generated by \`npm run docs:schema\` on ${now}`);
  lines.push(`> Source: SQLite DB introspection via PRAGMA table_info()`);
  lines.push(`> **${tables.length} tables** in schema`);
  lines.push("");
  lines.push("---");
  lines.push("");
  lines.push("## Table of Contents");
  lines.push("");
  for (const t of tables) {
    const anchor = t.tableName.replace(/_/g, "-");
    lines.push(`- [${t.tableName}](#${anchor})`);
  }
  lines.push("");
  lines.push("---");
  lines.push("");

  for (const { tableName, columns, indexes } of tables) {
    lines.push(`## ${tableName}`);
    lines.push("");

    // Columns table
    lines.push("| Column | Type | Nullable | PK | Default |");
    lines.push("|--------|------|----------|----|---------|");
    for (const col of columns) {
      const nullable = col.notnull ? "NOT NULL" : "nullable";
      const pk = col.pk ? "YES" : "";
      const dflt = col.dflt_value != null ? `\`${col.dflt_value}\`` : "—";
      lines.push(`| \`${col.name}\` | \`${col.type || "TEXT"}\` | ${nullable} | ${pk} | ${dflt} |`);
    }
    lines.push("");

    // Indexes
    if (indexes.length > 0) {
      const nonAutoIndexes = indexes.filter((i) => i.origin !== "pk");
      if (nonAutoIndexes.length > 0) {
        lines.push("**Indexes**");
        lines.push("");
        for (const idx of nonAutoIndexes) {
          const unique = idx.unique ? " (UNIQUE)" : "";
          lines.push(`- \`${idx.name}\`${unique} on \`${idx.columns.join(", ")}\``);
        }
        lines.push("");
      }
    }
  }

  return lines.join("\n");
}

/* ------------------------------------------------------------------ */
/* Main                                                                 */
/* ------------------------------------------------------------------ */
try {
  console.log("[docs:schema] Introspecting database…");
  const tables = introspectDb();
  console.log(`[docs:schema] Found ${tables.length} tables`);

  const md = generateMarkdown(tables);

  const dir = path.dirname(outputPath);
  fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(outputPath, md, "utf8");
  console.log(`[docs:schema] Written to ${outputPath}`);
  console.log(`[docs:schema] ${md.split("\n").length} lines generated`);
  process.exit(0);
} catch (err) {
  console.error("[docs:schema] Fatal error:", (err as Error).message);
  process.exit(1);
}
